### ISSUE TITLE
方块列表和色值表格式规范

### ISSUE THREAD

**Issue by Van-Nya** [Van-Nya/SlopeCraftR#5]
## 方块列表

我的建议如下

```YAML
<base_color_id_0>:
  - id: <block_id_00>
    id_old: <id_00_in_mc112>
    need_glass: <bool>
    is_glowing: <bool>
  - id: <block_id_01>
    id_old: <id_01_in_mc112>
    need_glass: <bool>
    is_glowing: <bool>
  ...
<base_color_id_1>:
  - id: <block_id_10>
    id_old: <id_10_in_mc112>
    need_glass: <bool>
    is_glowing: <bool>
  - id: <block_id_11>
    id_old: <id_11_in_mc112>
    need_glass: <bool>
    is_glowing: <bool>
  ...
...
```

将尖括号及其内容替换为具体的数据

## 色值表

我的建议如下

```CSV
Red     ,Green   ,Blue
00000000,00000000,00000000
<valueR>,<valueG>,<valueB>
...
```

将尖括号及其内容替换为具体的数据
